@startuml
'https://plantuml.com/class-diagram

/'abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}'/

abstract class Component {
String name
Component(name)
calcState()
}

class Taster{
Output out
Taster(output)
press()
release()
}

abstract class Node{
boolean state
Node(state)
getState()
setState(boolean)
}


class Input{
Component comp
Input(component)
}

class Output{
List<Input> inputs
Output(inputs)
}

class FF{
boolean state
Input set
Input reset
Output q
Output not_q
FF(name, set, reset, q, not_q)
calcState()
}

class LED{
boolean isOn
LED(boolean)
}

Component <|-- FF

Component <|-- LED
Node <|-- Input
Node <|-- Output
@enduml